default: sand

all: sand

sand:
	pdflatex sand.tex
	#bibtex sand
	#dflatex sand.tex
	pdflatex sand.tex

clean:
	rm -f sand.blg
	rm -f sand.bbl
	rm -f sand.pdf
	rm -f sand.log
	rm -f sand.lot
	rm -f sand.lof
	rm -f sand.out
	rm -f sand.toc
	rm -f sand.aux

